name: CI/CD Bare Minimum

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Start app (simulation)
        run: |
          npm start &
          sleep 5
          curl -f http://localhost:3000/api/health
          echo "✅ App is running"
