name: Security Analysis (SAST + SCA)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # ====================================
  # 🔍 SCA - Software Composition Analysis avec Snyk
  # ====================================
  snyk-scan:
    name: Snyk - Analyse des dépendances
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true  # Continue même si Snyk échoue (token non configuré)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high  # Bloque sur HIGH et CRITICAL
          command: test

      - name: Upload Snyk results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        continue-on-error: true
        with:
          sarif_file: snyk.sarif

  # ====================================
  # 🔍 SAST - Static Application Security Testing avec CodeQL
  # ====================================
  codeql-analysis:
    name: CodeQL - Analyse statique du code
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-extended  # Requêtes de sécurité avancées

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  # ====================================
  # 📊 Vérification des vulnérabilités npm audit
  # ====================================
  npm-audit:
    name: NPM Audit - Vérification des vulnérabilités
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=high  # Bloque sur HIGH et CRITICAL
        continue-on-error: false  # ❌ Bloque le pipeline si vulnérabilités

      - name: Generate audit report
        if: failure()
        run: npm audit --json > npm-audit-report.json

      - name: Upload audit report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: npm-audit-report.json

  # ====================================
  # ✅ Job final - Tous les checks doivent passer
  # ====================================
  security-gate:
    name: Security Gate - Validation finale
    runs-on: ubuntu-latest
    needs: [snyk-scan, codeql-analysis, npm-audit]
    if: always()

    steps:
      - name: Check if all security scans passed
        run: |
          echo "📊 Security Scan Results:"
          echo "  - Snyk: ${{ needs.snyk-scan.result }}"
          echo "  - CodeQL: ${{ needs.codeql-analysis.result }}"
          echo "  - NPM Audit: ${{ needs.npm-audit.result }}"
          
          # Snyk peut échouer si token non configuré, on ne bloque pas pour ça
          if [ "${{ needs.codeql-analysis.result }}" != "success" ] || \
             [ "${{ needs.npm-audit.result }}" != "success" ]; then
            echo "❌ Critical security scans failed! Pipeline blocked."
            exit 1
          else
            echo "✅ Security scans passed!"
            if [ "${{ needs.snyk-scan.result }}" != "success" ]; then
              echo "⚠️  Note: Snyk scan had warnings (configure SNYK_TOKEN for full analysis)"
            fi
          fi

      - name: Security validation successful
        run: echo "🎉 Code is secure and ready for deployment!"

